export const WOODESK_SET_USER = 'WOODESK_SET_USER';
export const WOODESK_RESET = 'WOODESK_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
